CONTRIBUTING.md
I made a couple of small tweaks here that improve the readability of this document.
=> Improve format of CONTRIBUTING.md

package.json
See fkling/esprima_ast_explorer#14
=> update esprima-fb to 15001.1.0-dev-harmony-fb

README.md
See #55 
Will happily modify if you have improvement suggestions on the format.
=> clarify how to pass options to recast

src/Collection.js
Correct an error message that indicates the opposite of what is being asserted.
=> Correct error message

src/Runner.js
=> fix path concatenation

src/core.js
Best Diff of the Year 2016
:stuck_out_tongue:
=> call → calling

README.md
=> grammar: a to an

README.md, recipes/retain-first-comment.md
[Reference](https://github.com/facebook/jscodeshift/issues/44#issuecomment-227315386).
Open to feedback on the example/verbiage/etc 😃
=> Add recipe for retaining leading comment in first statement within file

.editorconfig
Used [editorconfig-tools](https://www.npmjs.com/package/editorconfig-tools) to generate a config inferred from existing code in the repo.
Makes keeping the code style consistent a bit easier for contributors that have default editor settings for different preferences.
=> Add .editorconfig to root

.babelrc, package.json, src/__tests__/Collection-test.js, src/__tests__/Worker-test.js, src/__tests__/core-test.js, src/__tests__/matchNode-test.js, src/__tests__/template-test.js, src/collections/__tests__/JSXElement-test.js, src/collections/__tests__/Node-test.js, src/collections/__tests__/VariableDeclarator-test.js
As I wrote a test, I didn't get any of the fancy output of jest 15 so I upgraded. 
It makes the tests go from 56s to 17s :) https://github.com/facebook/jscodeshift/pull/155#issuecomment-249397496
=> Update to jest 15

src/Collection.js, src/Worker.js, src/__tests__/Collection-test.js, src/__tests__/Worker-test.js, src/__tests__/core-test.js, src/__tests__/matchNode-test.js, src/collections/JSXElement.js, src/collections/Node.js, src/collections/VariableDeclarator.js, src/collections/__tests__/JSXElement-test.js, src/collections/__tests__/Node-test.js, src/collections/__tests__/VariableDeclarator-test.js, src/core.js, src/ignoreFiles.js, src/matchNode.js, src/testUtils.js
=> leetspeak demo let and const transform

src/__tests__/template-test.js, src/template.js
=> Handle template replacement when recast traverses out of order

.eslintignore, .eslintrc, .jshintrc, src/__tests__/Collection-test.js, src/__tests__/template-test.js, src/collections/VariableDeclarator.js, src/collections/__tests__/JSXElement-test.js, src/collections/__tests__/VariableDeclarator-test.js, src/template.js
Feel free to let me know if any of them doesn't make sense. And I'm prepared to drop commits.
> 	@sharils 	sharils 	Fix eslint auto-fixable 			0403860
>	@sharils 	sharils 	Fix no-unused-vars 			fa7a693
>	@sharils 	sharils 	Add jest to eslint env 			f04a1ed
>	@sharils 	sharils 	Add .eslintignore 			2d44929
Because CONTRIBUTING.md says, "Make sure your code lints." And my `` yarn run eslint . `` doesn't pass.
> @sharils 	sharils 	Add jshint to devDependencies 			50cd81f
This one I'm not sure whether I should add jshint to devDependencies or delete .jshintrc. So I just choose an arbitrary one.
=> Codebase cleanup

package.json, src/Worker.js, yarn.lock
neo-async is a drop-in replacement for async which is faster.
=> Perf: replace async with neo-async

src/collections/VariableDeclarator.js, src/collections/__tests__/VariableDeclarator-test.js
=> Fix renameTo renaming React component prop name unexpectedly

package.json
Diff here: https://github.com/benjamn/recast/compare/v0.16.1...v0.18.1
=> Bump recast to ^0.18.1

CHANGELOG.md
Per discussion in https://github.com/facebook/jscodeshift/pull/297
=> Update changelog with #297

package.json
Fix for https://github.com/facebook/jscodeshift/issues/384
=> Added "license" field to package.json. Fixes #384

README.md, bin/jscodeshift.js, package.json, src/Runner.js
=> Add a flag to make jscodeshift return a 1 code when errors were found

README.md
Adding js usage to the README using `Runner.run`
related to #398
=> JS usage documentation

package.json
Refs: https://github.com/facebook/jscodeshift/pull/599#issuecomment-2229122985
=> Add SHA hash of yarn@1.22.22 in packageManager field

package.json, yarn.lock
Fixes: https://github.com/facebook/jscodeshift/issues/604
=> Remove unused dependency `node-dir`

README.md
Enhance README.md for adding '.json' to the code block.
=> Enhance README.md for adding '.json' to the code block.
