facebook/jscodeshift

README.md
bin/jscodeshift.sh

I found the description for this option to be confusing, partly because
I don't think "repeate" is actually a word, and partly because if it
was a typo for "repeat", it hardly makes sense to me here. In any case,
these words seem unnecessary and can probably just be removed entirely.
I also remove the two occurrences of trailing whitespace in the readme.

Improve description of -v option

---

src/Collection.js
src/__tests__/Collection.js
src/collections/JSXElement.js
src/collections/Node.js
src/collections/VariableDeclarator.js
src/collections/__tests__/JSXElement-test.js
src/collections/__tests__/VariableDeclarator-test.js

Note: This is not a breaking change. It only changes how collections are
represented internally and solves a couple of issues with the current
implementation.
ast-types defines a type hierarchy. For example, a "BlockStatement" has this
hierarchy:
BlockStatement <- Statement <- Node <- Printable
I.e. a "BlockStatement" is also a "Statement", a "Node", etc.
jscodeshift uses this hierarchy to model collection classes. Every collection
class inherits from its supertype/parent collection class. For example,
"BlockStatementCollection" inherits from a "StatementCollection",
etc.
Whenever `registerMethods(methods, type)` is called, classes for "type"
and all its supertypes are created, if they don't exist yet, and are extended
with "methods". This works (obviously) but has some disadvantages. The …

Change implementation of collections

---

CONTRIBUTING.md
bin/__tests__/jscodeshift-test.js
bin/jscodeshift.sh
scripts/test-preprocess.js
src/Collection.js
src/Runner.js
src/Worker.js
src/__tests__/Collection-test.js
src/__tests__/core-test.js
src/collections/JSXElement.js
src/collections/Node.js
src/collections/VariableDeclarator.js
src/collections/__tests__/JSXElement-test.js
src/collections/__tests__/Node-test.js
src/collections/__tests__/VariableDeclarator-test.js
src/core.js

Our `CONTRIBUTING.md` documentation tells us to prefer single quotes
over doubles, but on the very next line we tell people to do `"use
strict"`.
This commit makes us bow to our single-quote overlords consistently
everywhere.

Update `"use strict"` hints to follow style guidelines

---

.babelrc
.travis.yml
bin/__tests__/jscodeshift-test.js
package.json
src/Collection.js
src/__tests__/template-test.js
src/collections/Node.js
src/core.js
src/template.js

"Templates" may not be the right term for this, open to suggestions.
This adds three tagged templates to the core API:
- `jscodeshift.template.expression`
- `jscodeshift.template.statement`
- `jscodeshift.template.statements`
Their purpose is to make it easier to replace nodes with more complex constructs, without having to build the replacement AST yourself. For example, the following replaces all matching identifiers with a function
call:
```js
let {expression} = jscodeshift.template;
// replaces all `bar` identifiers with the function call `foo(bar)`
jscodeshift(src)
.find('Identifier', {name: 'bar'})
.replaceWith(path => expression`foo(${path.node})`);
```
The difference between the three function is just how the provided
code snippet is parsed:
- `expression` returns an expression …

[RFC] "Templates" -- first steps

---

src/collections/Node.js
src/collections/__tests__/Node-test.js

I've been working around this in my codemods so far, this makes it so that you can pass an array to these methods (or return an array from the replacer method). I also removed `functionify` and inlined it.
I also added tests for insertAfter.

Add support for arrays to replaceWith, insertBefore and insertAfter.

---

src/collections/Node.js
src/collections/__tests__/Node-test.js

Removing a node is hard. This is an initial implementation of a function `remove` that can remove a node if it is part of any AST field that is an array. I probably missed some but this should be a good start.
I'm not entirely sure what I should do in the case that the parent becomes empty. In some cases you'd want the parent to remove itself (empty block in a function?) but sometimes you probably don't (removing all params from a function, remove all items from an object expression). I think this is best left to the developer, although I'm wondering if we can provide hints. Should the `remove` method return something like `All expressions from a "SequenceExpression" were removed. You can now consider removing the SequenceExpression`?

[RFC] Remove node

---

bin/jscodeshift.sh
src/Runner.js
src/Worker.js

This uses babel's require hook. The downside is that every worker will transform every file, but workers are limited to number of CPUs so I think the overhead of doing this a few times isn't a big deal. Also added an option `babel` to disable this behavior.
Other solutions we've explored:
* Transform the script in the Runner and create a temp file. This breaks `require` calls in the transform script because the temp file would be relative
* Put the temp file into the same folder as the transform file. This means that `require` works but other files won't be transformed.

Pre-process transform files with babel. Fixes #5

---

README.md
bin/__tests__/jscodeshift-test.js
bin/jscodeshift.sh
package.json
src/Runner.js

This allows us to use jscodeshift without find/xargs which should really help with the cli ergonomics. I've been fighting with this all the time and got really annoyed, so glad I finally got around to change the Runner.
This makes use of `node-dir` and uses Promises. I converted the Runner code to ES6, pretty sure there are some subjective code style choices but I tried to make the style more "functional" and use const where appropriate.

Add ability to pass one or many directories to jscodeshift. Fixes #21

---

.eslintrc
bin/__tests__/jscodeshift-test.js
src/__tests__/core-test.js
src/core.js

There have been multiple reports about the printed source missing trailing line breaks. The reason for the line break missing is that this information is contained in the `File` node, which is returned by
`recast.parse`.
However, because we build a node collection from the `Program` node instead of the `File` node, we are loosing this information.
Using the `File` node fixes the issue and doesn't seem to break any existing functionality.

Fix printing

---

src/Runner.js

There is no "cpus" variable at that point, which breaks the Math.min() expression and as a result, no workers are spawned if the -c option is used.
"availableCpus" seems to be the variable that was meant to be used and fixed the problem for me.

Fix for "cpus" command line parameter

---

src/Collection.js
src/__tests__/Collection-test.js

Adds support for negative indices to conveniently refer to needed nodes without saving them to local vars.

Collections: support negative indicies

---

src/__tests__/matchNode-test.js
src/matchNode.js

Makes a couple improvements to `matchNodes`:
- Allow `path.find(j.Identifier, node => WHITELIST.hasOwnProperty(node.name))`.
- Fix fatal in `path.find(j.Identifier, {loc: null})`;
Also, added unit tests.

Improvements to matchNode

---

bin/jscodeshift.sh
src/Runner.js
src/Worker.js

Like jest's `--run-in-band` so you can use `--debug/-brk` without hating life. If the `if (module.parent) {` block is too gross, then I'm open to suggestions. cc: @fkling @cpojer

Add '--run-in-band' option to run in the current process

---

bin/__tests__/jscodeshift-test.js
bin/jscodeshift.sh
src/Runner.js

issue ref: https://github.com/facebook/jscodeshift/issues/60

Add '--silent' or '-s' option to suppress output

---

src/Worker.js

Hi!
This PR prevents jscodeshift's Babel from picking up external Babel configuration.
See [this](https://github.com/facebook/jscodeshift/issues/84) issue for more information.

Disable external Babel configuration

---

src/Runner.js

Before, Runner would print 1.023 as "1.23 seconds".

Fix time elapsed display

---

src/Runner.js

Re-implement the function `dir.files` that walks directories to collect files.
The main change is that when stat problems are encountered (e.g., due to symlink issues), we log an error but continue on, instead of refusing to any work.

fix symlink problems

---

bin/__tests__/jscodeshift-test.js
src/Runner.js
src/Worker.js

Change the worker management to be dynamic rather than static. Instead of dividing all files among the available number of processes, we now send chunks of work to each free process, and when a process finishes its chunk of work it gets another chunk. This leads to overall much better perf for a large number of files with non-uniform processing times.

worker optimization

---

src/Runner.js

The worker was being called more than once when in run-in-band mode.

Fix processes count and chunk size for run-in-band mode

---

src/Runner.js

The [`write` method on Stream][write] takes the second argument to be an encoding. This is certainly not what's needed in the log messages.
If you run `jscodeshift -v 2` on a file, you can get `TypeError` exceptions.
[write]: https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback

Fix encoding errors in logging messages

---

src/Worker.js

I can consistently reproduce a problem with `jscodeshift` where all the transformations are applied correctly, but the process doesn't exit--it just hangs. It may be related to the problem that is described by @ForbesLindesay in #87.
This is solved by forcing child workers to execute `process.disconnect` at the beginning of their next event loop interation instead of during the event loop interation in which they are processing their final message. The relevant documentation is in the [Node docs][disconnect-docs].
> The 'disconnect' event will be emitted when there are no messages in the process of being received. This will most often be triggered immediately after calling child.disconnect().
Unfortunately, the files I've used to produce this behavior are part of a proprietary piece of …

Fix process disconnection

---

package.json
src/Runner.js

Swap out `cli-color` dep for `colors` since it has no dependencies.
I'm having a lot of problems with `cli-color` deps `es5-ext` and `es6-iterator` since they have folders named `#` which gets dropped by mercurial by default. Additionally these deps have non utf8 files which are causing problems. It seems kinda overkill when all we want are some color codes so lets just use the simple `colors` module.

cli-color -> colors

---

.npmignore
README.md
package.json
sample/__testfixtures__/reverse-identifiers.input.js
sample/__testfixtures__/reverse-identifiers.output.js
sample/__tests__/reverse-identifiers-test.js
sample/reverse-identifiers.js
src/testUtils.js

Adds a simple utility to allow unit testing of jscodeshift transforms in a standard way, without having to write a bunch of boilerplate code. This is loosely based off [the technique used in react-codemod](https://github.com/reactjs/react-codemod/blob/master/jest/env.js#L23), with some changes. The main change is that where possible it doesn't depend on any global environment/configuration:
- It's in an actual module rather than a global function called "test". It took me *so long* to work out where the `test` function was coming from in the `js-codemod` repo :stuck_out_tongue: 
- Assumes the transform is in the parent directory of the test (eg. transform is at `foo/bar.js`, test is at `foo/__tests__/bar-test.js`)
- Does not use a `.js` suffix for the test fixtures (input and expected …

Add simple utility for unit testing jscodeshift transform

---

src/__tests__/core-test.js
src/core.js

Provides a `use` method on core that can be used to register extensions.
It avoids calling the same extension multiple times which is useful during testing.

Provide plugin registration method that avoids duplicate registrations.

---

package.json

Fixed the issue of not printing return type in arrow function expressions (benjamn/recast#289). Thanks!

Upgrade recast to ^0.11.8

---

README.md
bin/jscodeshift.sh

Added _super_ basic documentation to highlight that [remote transforms can be used](https://github.com/facebook/jscodeshift/commit/027cd027800e238e35d047654360ba08d8e3f7ea). Let me know if there are any suggestions for better verbiage.
Also, I think it might be useful to specify the limitations of this feature (primarily, that the transform must be entirely self-contained). Any suggestions on where to include that in the README?

Add note about remote transforms to CLI --help and readme

---

.eslintrc
.npmignore
.travis.yml
README.md
bin/__tests__/jscodeshift-test.js
bin/jscodeshift.sh
package.json
packages/babelv5/index.js
packages/babelv5/package.json
parser/babylon.js
sample/__tests__/reverse-identifiers-test.js
sample/reverse-identifiers.js
src/Runner.js
src/Worker.js
src/__tests__/.eslintrc.yaml
src/__tests__/.jshintrc
src/__tests__/Collection-test.js
src/__tests__/Worker-test.js
src/__tests__/core-test.js
src/__tests__/matchNode-test.js
src/__tests__/template-test.js
src/collections/Node.js
src/collections/__tests__/JSXElement-test.js
src/collections/__tests__/VariableDeclarator-test.js
src/core.js
src/getParser.js
src/template.js
src/testUtils.js
utils/requirePackage.js
utils/testUtils.js

jscodeshift uses Babel v5 to parse source files. Since Babel v5 doesn't get updated anymore, jscodeshift is unable to parse files that contain more modern flow type annotation.
To solve this, jscodeshift now supports three parsers: Babel v5, babylon and flow. The parser to use can be chosen by either
- passing the command line option `parser`: `--parser=babelv5`,
`--parser=babylon`, `--parser=flow`.
- having the transform file export `parser`, with either the values
`"babelv5"`, `"babylon"` or `"flow` to choose one of the built-int
parsers, or export a parser object (e.g. `exports.parser = require('flow=parser'`)
This allows transform to specify their own parser (as long as it is compatible with ESTree / recast), making them a bit more independent from jscodeshifts internals.
In addition …

Add the possibility to select different parsers (closes #117)

---

package.json

lodash v3 has an issue that causes `TypeError: Cannot read property 'prototype' of undefined` when we set Jest's `testEnvironment` to `node`. This has been fixed in v4 (lodash/lodash#223).
Thanks for reviewing! cc @cpojer

Upgrade lodash to v4

---

src/collections/VariableDeclarator.js
src/collections/__tests__/VariableDeclarator-test.js

The old code to filter out member expression properties was broken (should be no ! before the computed check), and there are also other cases where an identifier is not a variable name.

Fix renameTo to ignore non-variable identifiers

---

src/Runner.js

This allows for jscodeshift to be used first class for doing simple static analysis reporting.
For example I am using this change to detect and print out `process.env[VARIABLE]`s accessed and track our analytics calls to automate documenting what has been implemented and what still needs to be implemented.

Include stats and timing information in node API

---

src/Runner.js

Consider the case where there's only 1 CPU

---

package.json

Thanks for including a lint config!
I have my editor setup to always use a packages local copy of `ESLint` to prevent possible version /config problems. Noticed it failing out when working on #126.
Any problems with adding them? I can work-around it if not.

Add eslint and babel-eslint to devDeps

---

package.json
src/Collection.js
src/collections/JSXElement.js
src/collections/Node.js
src/collections/VariableDeclarator.js
src/core.js

This is a first stab at getting auto-generated documentation for traversal/mutation methods setup. I currently have it building the docs to `/docs`, in hopes that it will work with the new GitHub pages setup (you don't need a separate branch for a project page anymore 🎉 ).
This will need more work, but I figured I'd submit progress so far and iterate.
Should also note that my `editorconfig` setup auto-removed some trailing spaces in places. Let me know if you want me to revert those changes.
I also attempted to use [DocumentionJS](https://github.com/documentationjs/documentation) and [ESDoc](https://esdoc.org/) for this, but they both didn't support enough of the JSDoc syntax that would be needed to generate docs for how this code is currently structured.

Start setting up auto-generated documentation

---

src/Collection.js
src/__tests__/Collection-test.js
src/collections/Node.js
src/collections/__tests__/JSXElement-test.js
src/collections/__tests__/Node-test.js
src/collections/__tests__/VariableDeclarator-test.js

Implements #150 (assuming it is wanted).
I was going to use [`util.deprecate`](https://nodejs.org/api/util.html#util_util_deprecate_function_string), but cannot do that without using the class fields proposal, so I'm just writing a warning to `stderr` atm.
`EditorConfig` setup in Atom killed some extra whitespace. Happy to revert if requested.

Deprecate Collection#size(), add Collection#length

---

src/Worker.js
src/__tests__/Worker-test.js

This way we can write
```js
export default function transformer(file, { j }) {
return j(file.source).toSource();
}
```
and not need to have the annoying local variable
```js
export default function transformer(file, api) {
const j = api.jscodeshift;
return j(file.source).toSource();
}
```

Add j shorthand

---

package.json
src/Worker.js

Instead of directly overwriting each JS file with its new contents, the worker
code now writes the new contents to a temporary file and then does a filesystem
move operation to overwrite the old file. This avoids the previous behavior
where the file had invalid contents while it was being written (because
`writeFile` is not atomic).
This fixes a race condition I was seeing in a script I was running on a large codebase:
https://github.com/alangpierce/bulk-decaffeinate/blob/master/jscodeshift-scripts/fix-imports.js
The script fixes import statements across the codebase by reading the exports
of the referenced files (using `readFileSync` and using jscodeshift to parse
the other file). Because the other files were also being transformed by
jscodeshift, sometimes (nondeterminsitically) some …

Atomically write transformed JS files back to the filesystem

---

recipes/retain-first-comment.md

The comments on the first line would be duplicated if the first node was not modified.
https://github.com/5to6/5to6-codemod/issues/18
https://github.com/facebook/jscodeshift/issues/44#issuecomment-271335348

Update first-comment recipe for when the first node is not updated

---

package.json
src/Runner.js

Promises are native in [all required `node` versions](https://github.com/facebook/jscodeshift/blob/master/package.json#L20).

Drop `es6-promise`.

---

src/__tests__/template-test.js
src/template.js

Let's parse a function expression with `jscodeshift.template.expression`:
```js
expression`function() {}`
```
This code is a valid expression, but not a valid statement -- a function needs to have a name to be a valid statement.
`template.expression` surrounds the code with `()` to force parsing as expression. However, it fails to do so if the template string doesn't have any interpolation parameters. Therefore, the above function expression fails to parse.
This PR fixes that bug -- the length of the `template` array is incorrectly checked. It should check for `length === 1` instead of `length === 0`. Moreover, a special case for `length === 1` is not even necessary.

template.expression should not parse string without interpolation as statement

---

package.json

Tests pass.
This version of recast includes a fix to iife wrapping when using babylon parser.

Bump recast to latest version

---

package.json

This version includes https://github.com/babel/babylon/pull/565 which was breaking `recast` on any code with Flow function type params.

Bump babylon version to latest stable

---

README.md
sample/__tests__/reverse-identifiers-test.js
src/testUtils.js

Closes https://github.com/facebook/jscodeshift/issues/203

Adding the ability to write tests inline, without fixture files

---

package.json
parser/babel5Compat.js
src/collections/__tests__/JSXElement-test.js
src/collections/__tests__/VariableDeclarator-test.js
src/getParser.js
yarn.lock

See https://github.com/facebook/jscodeshift/issues/229
We can get rid of Babel5 as the dependency on Babylon is enough to make the tests pass, as long as we use Babylon in the same way Babel5 used to use it under the hood

Replace babel-5 parser with retrocompatible babylon setup

---

src/template.js

The current code causes duplicate variable names due to there being no guarantee that `Math.random()` will return non-colliding values. This is especially true given the 32-bits of the V8 `Math.random()` implementation.
This change replaces the use of `Math.random()` with a simple counter to guarantee that each name returned is different.

Guarantee uniqueness of variable names

---

src/Runner.js

The reject handler were always called no matter if there was an or not.
Now it will properly test for that and also wait for the write to be done before closing fd.
It will also report an error including a stack trace from now on and not only show a error message in case there is an error in the http(s) call.
I also fixed the issue that the write did not have a callback at all, so that error was always silent so far. This is going to throw from Node.js 10.x on. See https://github.com/nodejs/node/pull/18668.

Fix error handling for http

---

README.md
sample/__tests__/reverse-identifiers-test.js
src/testUtils.js

This is a small change that makes test output a bit nicer when writing
multiple inline tests.

Allow specifying a testName for inline tests

---

src/collections/VariableDeclarator.js
src/collections/__tests__/VariableDeclarator-test.js

This fixes the `renameTo` helper method not properly renaming object properties that are shorthands.
Bug reproduction in AST Explorer: http://astexplorer.net/#/gist/0ad1434f08e1720089d7085fbdfe7ba0/6f6632f0bb6e2e3aa77d5e873d0ab05d6c3be0e3
The previous version of the code would rename the property's `value` correctly, but since `shorthand` was still set as `true`, the output result would still be the old variable as a shorthand
property.
Now, if an identifier to be renamed is of type `Property` and is a shorthand (but not a method), we flip the `shorthand` value to be `false`.
Added a test for this as well.

Fix `renameTo` not taking property shorthands into account

---

package.json
parser/babel5Compat.js
parser/babylon.js
yarn.lock

This enables 
- the `a?.b` optional chaining operator
- the `a ?? b` nullish coalescing operator
- the `12__32__43` numerical separators syntax

Enable parsing `?.`, `??`, and numeric separators

---

parser/flow.js

`tokens` is an undocumented flag that adds the tokens to the output ast.
https://github.com/facebook/flow/blob/master/src/parser/libflowparser.ml#L60
This is necessary for the newest version of recast, which will use the esprima parser if the tokens aren't present: https://github.com/benjamn/recast/blob/master/lib/parser.js#L44-L48. The esprima parser doesn't parse JSX, which makes running jscodeshift on files with jsx in them fail when relying on the new version of recast. To repro, update the recast version and run a codemod on a file with JSX-- you will get a parse error.
It will be necessary to upgrade the recast dependency in order to support the new `...` syntax for flow inexact objects.
Is there a reason not to include all of the proposal parsers? I enabled optional chaining and …

Enable more flow parser options

---

bin/jscodeshift.sh
package.json
parser/babel5Compat.js
parser/babylon.js
yarn.lock

In order to support explicit flow type arguments, this PR upgrades the babylon parser from babylon 6 to @babel/parser ^7.0.0.
Example of new syntax:
```js
// @flow
const a = b<stirng>();
```

Add support for explicit flow type arguments

---

README.md
bin/jscodeshift.sh
parser/ts.js
parser/tsOptions.js
parser/tsx.js
src/getParser.js

Add parsers for TypeScript and TSX to make it easier to use jscodeshift for TypeScript projects.
Babel options were taken from https://github.com/benjamn/recast/blob/master/parsers/_babel_options.js
A separate parser for TSX was added because there are language constructs that have a different meaning depending on whether the file is TSX or not, such as `<type>` syntax for casting (which was mentioned here https://github.com/benjamn/recast/pull/535).
Example Usage:
```
jscodeshift -t sample/reverse-identifiers.js --extensions ts,tsx --parser tsx all-the-code
```
Reviewers: @fkling @cpojer 
cc @benjamn

Add parsers for TypeScript and TSX

---

package.json

See diff here: https://github.com/benjamn/recast/compare/v0.15.5...v0.16.1
Notably, this includes some bugfixes for type support.
to: @brieb @fkling

Bump recast to ^0.16.1

---

bin/__tests__/jscodeshift-test.js
parser/ts.js
parser/tsx.js

Previously, the TypeScript parser would fail due to the 'babylon' package having the incorrect version (v6). Added a test which will detect this:
```
● jscodeshift CLI › --parser=ts › parses TypeScript sources
expect(string).not.toContain(value)
Expected string:
"Processing 1 files...
ERR /var/folders/ms/t3l222rn1v3dkvvnytj4vfkw0000gn/T/f-118113-6659-hurec.taoyh Transformation error (Unexpected token, expected ; (1:5))
SyntaxError: Unexpected token, expected ; (1:5)
```
Switching to '@babel/parser' fixes this.

Use @babel/parser in TypeScript parser

---

src/Runner.js

In case no files are found then jscodeshift crashes with a `TypeError` as `pendingWorkers` are `undefined`, so `Promise.all(pendingWorkers)` will fail.
Output before this PR:
```
No files selected, nothing to do. 
(node:56389) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
at Function.all (<anonymous>)
at getAllFiles.then.then.pendingWorkers (/node_modules/jscodeshift/src/Runner.js:292:17)
(node:56389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:56389) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the …
```

Fix TypeError in case no files were found

---

src/ignoreFiles.js

I tried to use jscodeshift in a repo that had a .gitignore that used `\r\n` as the newline character, and it crashed inside of snapdragon (used by minimatch) because all of the file globs had trailing `\r`s.
This PR cleans up trailing `\r`s and also prevents .gitignore comments from being treated as globs.

Improve handling of .gitignore files.

---

src/testUtils.js

Since we are able to write transformers in TS, the .js extension hard coded in testUtils not allow us to use it to write tests for TS transform modules.
And `require('some-module')` will automatically infer some-module's extension whether it is ended with '.js' or '.ts', it should be safe to remove ',js'.

Remove transform file .js restriction for testUtils

---

README.md

This PR updates "Typescript" &rarr; "TypeScript" in README file.

Use canonical capitalization of TypeScript

---

src/Runner.js

When jscodeshift is called with a path that doesn't exist, `concatAll()` gets called with `undefined`, which isn't an iterable, and throws an error. This PR fixes the promise being resolved by matching it with the ignore case.

Fix Unhandled Promise rejection when called with a non-existent path

---

src/Runner.js

There is behavior in this program that depends on the extension
of the transformFile, notably how babel runs (or doesn't).
There was a bug when requesting a remote transformFile authored as
an ES6 module because of the temp filename being used.
This commit preserves the original file extension used when writing
the remote file to the temp one.
Fixes https://github.com/facebook/jscodeshift/issues/316

fix: preserve file extension for remote file

---

yarn.lock

Apparently there is a security issue with an outdated version of `eslint-utils`. Address that by running `yarn upgrade eslint`.
Test Plan:
```
$ npm test
PASS  src/utils/__tests__/intersection-test.js
PASS  src/utils/__tests__/union-test.js
PASS  src/utils/__tests__/once-test.js
PASS  src/__tests__/argsParser-test.js
PASS  src/__tests__/matchNode-test.js
PASS  src/__tests__/core-test.js
PASS  sample/__tests__/reverse-identifiers-test.js
PASS  src/collections/__tests__/JSXElement-test.js
PASS  src/collections/__tests__/VariableDeclarator-test.js
PASS  src/collections/__tests__/Node-test.js
PASS  src/__tests__/template-test.js
PASS  src/__tests__/Worker-test.js
PASS  src/__tests__/Collection-test.js
PASS  bin/__tests__/jscodeshift-test.js (20.751s)
Test Suites: 14 passed, 14 total
Tests: …
```

Upgrade eslint dev dependency

---

README.md
src/testUtils.js

The main benefit of this PR is actually the `applyTransform` function, since it can be used for a lot of things.
- Refactored `runInlineTest` and extracted `applyTransform` function
- Introduced `runSnapshotTest`, same as `runInlineTest` but takes no `expectedOutput`
- Introduced `defineSnapshotTest`, same as `defineInlineTest` but takes no `expectedOutput`
- `runInlineTest` and `runSnapshopTest` now both also return the result `applyTransform`
- This can be used to take the result of one run and use it for another test (check for idempotent)

Introduce jest snapshot testing utils (fixes #135)

---

sample/__testfixtures__/typescript/reverse-identifiers.input.ts
sample/__testfixtures__/typescript/reverse-identifiers.output.ts
sample/__tests__/reverse-identifiers-test.js
src/testUtils.js

`jscodeshift` now supports TypeScript (and other parsers) via the CLI. The `react-codemod` package can now support different React codebases. 
In order to use the `defineTest` helper in `testUtils.js` with different parsers the `defineTest` function needs to allow dynamic parsers and look at different extensions (for TypeScript: `.ts`, `.tsx`).
The approach used in this PR was to add another parameter `testOptions` that allows passing in an object with a `parser` key. The extension then can be inferred from the file being parsed.
I didn't feel great about adding another parameter so I opted for an object so if there are additional config options they can be added to this object rather than adding more arguments and passing many `null`s to get to the proper position. I also considered …

Support different parsers in the test utils

---

CHANGELOG.md
package.json
yarn.lock

Update flow-parser to 0.113 and increment the patch number to prepare for cutting a release.

Bump flow parser and jscodeshift version

---

src/ignoreFiles.js

I was checking `jscodeshift` and `micromatch` source code and saw that `.any` is there for backward compat, and they renamed it to `.isMatch` 
https://github.com/micromatch/micromatch/blob/fe4858b0c63b174fd3ae22674db39119b8fa4392/index.js#L126

Rename micromatch any to isMatch

---

.travis.yml
package.json
src/Worker.js
yarn.lock

`@babel/preset-env` is a very large dependency to determine which plugins to use in node. In this PR I'm making it optional, dropping support for Node 8 and below (which have been deprecated for years) and added common syntax transforms to make jscodeshift transforms run in Node 10+.
The behavior will be unchanged if `@babel/preset-env` is already part of node_modules, otherwise it needs to be installed by the user. This will be released as jscodeshift 0.8 to make it non-breaking.

Make @babel/preset-env optional, drop support for Node 8 and below

---

package.json
yarn.lock

Currently jscodeshift errors when it encounters [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
`Error: did not recognize object of type "ChainExpression"`
Ast-types and reacast where [recently updated](https://github.com/benjamn/ast-types/pull/399) to support ChainExpressions this pr bump fixes jsShift errors on chainexpressions

chore: update recast to allow ChainExpression types

---

src/Worker.js

Hello. Wanted to float this, as a way to allow transforms to be async. This unlocks any kind of transform that would want to query some exterior piece of state.

Allow transform to be a promise. Resolves #210.

---

package.json
yarn.lock

With `temp@0.8.3` installed and the `babel` option enabled, Babel throws due to the legacy octal literals used within `temp/lib/temp.js`:
```
SyntaxError: /.../node_modules/temp/lib/temp.js: Legacy octal literals are not allowed in strict mode. (226:20)
224 | function mkdir(affixes, callback) {
225 |   var dirPath = generateName(affixes, 'd-');
> 226 |   fs.mkdir(dirPath, 0700, function(err) {
|                     ^
227 |     if (!err) {
228 |       deleteDirOnExit(dirPath);
229 |     }
```
It looks like this issue was fixed in `0.8.4`, which uses `parseInt` instead. Most packages would automatically be using this newer version regardless, but I ran across a few at my org where after upgrading `jscodeshift` I'd hit this issue since `temp` was locked to an older version. Making the dep a …

Make dependency on temp version slightly stricter

---

package.json
parser/__tests__/.eslintrc
parser/__tests__/__snapshots__/tsx-test.js.snap
parser/__tests__/tsx-test.js
parser/tsx.js

Resolves #418
Replaces https://github.com/facebook/jscodeshift/pull/427
Opening a new PR with some added tests and the suggested fixes since the last PR has set for a few weeks now. Feel free to close this in favor of the PR added by @robyoder, but this bug is painful enough for my use case that I'd love to see it get fixed and released, so figured I'd quickly do some of the legwork for testing it out 😄.
The PR:
* Removes the undeclared dependency on lodash
* Stops overriding the value of `asyncGenerators` in the plugins array with `jsx`
* Stops mutating the return value of `tsOptions`

Remove lodash dependency from tsx parser 

---

src/__tests__/template-test.js
src/template.js

allows things like `` asyncExpression`foo ? await bar : baz` ``
I was tempted to make `expression` itself support this, but it has to wrap the code in `async () => (...)`, and theoretically some user-supplied parsers might not support async functions.

feat: create template.asyncExpression

---

package.json
src/Runner.js
yarn.lock

a denial of service via an infinite loop has been introduced into the latest version of colors and not in chalk
https://security.snyk.io/vuln/SNYK-JS-COLORS-2331906
As this was intentionally introduced by the developer, migrating seems to be the best course

fix: use chalk as a dependency instead of colors

---

README.md

One of the code blocks was using tabs instead of spaces, which was inconsistent with the rest of the README.

Tabs to spaces in code examples for consistency

---

README.md
sample/__tests__/__snapshots__/reverse-identifiers-test.js.snap
sample/__tests__/reverse-identifiers-test.js
src/testUtils.js

Adds a wrapper function, `defineSnapshotWithFixture` around `defineSnapshotTest` that mimics the loading/parsing behavior of `defineTest` to load the file based on the testFilePrefix in the `__testfixtures__` directory. Adds a quick test in the sample directory as well as updates documentation.

feat: add a snapshot test util that loads the file for users

---

package.json
yarn.lock

Refs https://github.com/facebook/jscodeshift/issues/490

Bump micromatch from 3.1.10 to 4.0.4

---

package.json
src/__tests__/Worker-test.js
yarn.lock

I attempted bumping to jest 27.x in https://github.com/trivikr/jscodeshift/pull/3 but there are [too many breaking changes](https://jestjs.io/blog/2021/05/25/jest-27#miscellaneous-breaking-changes).
The jest 27.x bump can be attempted after merging changes from evcodeshift fork.

chore(deps-dev): bump jest to 26.x

---

README.md

Adds info about how do in-IDE debugging with the VSCode debugger to the README.
It would of course be handy if others testing out this functionality to see if this approach works for them or whether the documentation could be clearer. 
Ideally, this functionality would eventually be able to be turned into a full blown VSCode extension.

Adding VSCode debugging setup

---

src/collections/VariableDeclarator.js
src/collections/__tests__/VariableDeclarator-test.js

Was not able to get in touch with @henryqdineen, so putting in this PR to origin.

Add renameTo filters for Babel 6+ node types

---

bin/jscodeshift.js
src/argsParser.js

Previously, the arg parser would display the arguments in the help section in alphabetical order. If you run ```jscodeshift -h``` you've notice all the arguments are displayed in alphabetical order. The algorithm that prints out the help page actually relies on them being in alphabetical order. The problem with this approach is that if there's a command that should be included in a category of arguments that appears in the middle of the page, but the new argument starts with a "z", then the new argument will appear in the last lines on the help page, and not in the middle where it's supposed to be.
Since we're need to move in the direction of grouping arguments by functionality independent of names (like for upcoming --gitignore flag), we now have to come up with a quick refactoring that …

Removing dependency on args being in alphabetical order.

---

src/collections/JSXElement.js
src/collections/__tests__/JSXElement-test.js

I wanted a function to get react children nodes that also works well with typing so that the collection returned will be of a specific JSXElement type (e.g. `JSXExpressionContainer`)
type defintion would look something like this:
```
childElements<T>(jsxChildElementType: types.Type<T>): Collection.Collection<T>;
```

add childNodesOFType to JSX traversalMethods

---

src/testUtils.js

Since the API allows the `j` shortcut, the mock test API should implement it as well.

Allow the j shortcut in testUtils

---

.github/workflows/test.yml

- drop node12 support from github-actions (EOL since 2022-04-30)
- add support for node18

chore(github-actions): drop node12 support node18

---

bin/__tests__/jscodeshift-test.js
package.json
parser/__tests__/__snapshots__/tsx-test.js.snap
src/__tests__/Collection-test.js
src/__tests__/matchNode-test.js
src/__tests__/template-test.js
src/collections/__tests__/JSXElement-test.js
src/collections/__tests__/Node-test.js
src/collections/__tests__/VariableDeclarator-test.js
yarn.lock

fixed breaking changes introduced in v27: https://jestjs.io/blog/2021/05/25/jest-27#miscellaneous-breaking-changes
fixed snapshot format in v29: https://jestjs.io/blog/2022/08/25/jest-29

chore(dev-deps): bump jest to v29

---

src/testUtils.js

The `defineTest` and `defineSnapshotTestFromFixture` functions currently require an explicit `testOptions` when working with Typescript textfixtures, such as [in this example](https://github.com/chimurai/jscodeshift-typescript-example/blob/main/examples/__tests__/reverse-identifiers.spec.ts#L4).
```tsx
const transform: Transform = (file, api) => {
// ...
}
export default transform;
export const parser = 'ts';
```
```tsx
defineTest(__dirname, 'MyTransform', null, null, { parser: 'ts' });
```
However, when a transform file [exports a ts or tsx parser](https://github.com/facebook/jscodeshift#parser) it would be more convenient if these functions could use that, and avoid needing to write `'ts'` twice across files.
When `testOptions.parser` is not explicitly defined, fallback to reading …

fix: Use transform's exported parser in testUtils

---

src/Worker.js

JSCodeShift is transpiling transform files given as arguments, and it is currently ignoring package-wide `.babelrc` settings file in `@babel/register` so that it shows a consistent behavior across many packages. 
However, since `configFile` option is not set to false, it is still affected by the project-wide `babel.config.js` settings file. Hence in some cases JSCodeShift may behave differently, depending on the settings of `babel.config.js`.
This PR fixes this behavior by setting `configFile: false` option to `@babel/register`, so that JSCodeShift behaves completely independent of the project-wide settings of babel.

fix: Set `configFile: false` option in `@babel/register`

---

package.json
yarn.lock

Typescript 4.9 added [a new `satisfies` operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html)
Files written in ts4.9 fail jscodeshift as of now. `recast` needs to be upgraded so that `ast-types` is upgraded past `v0.16.0` which is when support for `TSatisfiesExpression` was added.

Upgrade recast to 0.23.1

---

.github/workflows/test.yml

Updated workflows to cache dependencies using [actions/setup-node](https://github.com/actions/setup-node#caching-global-packages-data). `setup-node@v3` or newer has caching **built-in**.
Jobs on GitHub-hosted runners start in a clean virtual environment and **must download dependencies each time**, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate files like dependencies, GitHub can cache files that frequently use in workflows.
Node.js projects can run faster on GitHub Actions by enabling dependency caching on the [setup-node](https://github.com/actions/setup-node) action. 
```yml
- name: Use Node.js ${{ matrix.node-version }}
uses: actions/setup-node@v2
with:
node-version: ${{ matrix.node-version }}
```
```yml
- …
```

chore(github-actions): Use setup-node action to cache dependencies

---

.gitattributes
bin/jscodeshift.js

This PR forces LF line endings for bin/jscodeshift.js and removes the spaces added after the shebang pragma in #549. I believe the spaces are not necessary as long as the line endings are LF and not CRLF.
See my comment about [Bun](https://bun.sh/) here: https://github.com/facebook/jscodeshift/pull/549#issuecomment-1493142756

Force LF line endings in bin/jscodeshift.js and remove spaces after shebang

---

package.json
yarn.lock

Minor version bump to pick up [these changes](https://github.com/benjamn/recast/compare/v0.23.1...v0.23.3) including:
- fix export specifier printing to enable mixed value/type declarations (i.e. `export { someValue, type someType }`)
- fix an issue that moved comments inside a call expression
Also updates `caniuse-lite` as its so old the out-of-date warning breaks tests.

Update recast for new features and fixes

---

src/Runner.js

Resolves https://github.com/facebook/jscodeshift/issues/561

Respect extensions cli option when filtering individual files

---

src/Worker.js

fix(worker): Update Worker.js

---

bin/__tests__/jscodeshift-test.js
package.json
utils/testUtils.js
yarn.lock

Fixing unit tests that were broken because the unit test framework by default looks for an extension with .js and the tempfiles created did not have a .js extension. Which wasn't problem, until #562 finally got the single file filter functionality working the way it was supposed to all along.

fix(unit tests): Fix for unit tests broken by #562

---

bin/jscodeshift.js

Fixes: https://github.com/facebook/jscodeshift/issues/582
The `ts` files are not processed by default
```console
$ ../jscodeshift/bin/jscodeshift.js example.ts 2>&1 | head -n 1
No files selected, nothing to do.
```
The extensions had to be explicitly passed
```console
$ ../jscodeshift/bin/jscodeshift.js --extensions=ts example.ts 2>&1 | head -n 1
Processing 1 files...
```
By default, the extensions is set to `js`
```console
$ ../jscodeshift/bin/jscodeshift.js --help | grep -A 1 extensions
--extensions=EXT          transform files with these file extensions (comma separated list)
(default: js)
```
The `ts` files are processed without requiring to pass extensions
```console
$ ../jscodeshift/bin/jscodeshift.js example.ts 2>&1 | head -n 1
Processing 1 files...
```
The `ts` files are skipped …

Process all supported JavaScript extensions by default

---

README.md
bin/__tests__/jscodeshift-test.js
src/Runner.js

Adds a --gitignore flag that uses a .gitignore file in the current working directory to force jscodeshift to abstain from transforming files that match patterns specified in the .gitignore file.
Please note that this feature is added primarily for the benefit of beginners to jscodeshift, as a way to make the enormously timesaving technique of passing a project's .gitignore file to jscodeshift easily discoverable and learnable. The idea is that when the user looks at the jscodeshift help page, "--gitignore" jumps right out at them and they immediately make the connection.
It took me a year and a half of using jscodeshift before I realized I could simply just pass .gitignore to the utiliity, and creating a new ignore file for a freshly cloned project every day is an annoyance I wouldn't …

Adding --gitignore flag

---

website/src/content/docs/run/cli.mdx

The [usage](https://jscodeshift.com/run/cli/#usage) instructions for jscodeshift cli options 2 through 4 were identical, which seemed confusing, so I updated the descriptions for options 3 and 4 to reflect their respective functionalities.

docs: clarify usage options

---

website/src/content/docs/build/api-reference.mdx

Added missing explanation of the [`nodes`](https://github.com/facebook/jscodeshift/blob/main/src/Collection.js#L158) method.

docs: add description for `nodes` api

---

website/src/content/docs/build/api-reference.mdx

The [current description](https://jscodeshift.com/build/api-reference/#getvariabledeclarators) of getVariableDeclarators seems to be inaccurate (it says it takes a string as an argument, like findVariableDeclarators, but the actual argument is a callback), so I fixed it.
See also: https://github.com/facebook/jscodeshift/blob/main/src/collections/Node.js#L103

docs: update getVariableDeclarators description

---

CONTRIBUTING.md
package.json

Fixes: https://github.com/facebook/jscodeshift/issues/598

Use corepack for managing yarn version

---

package.json
src/Runner.js
yarn.lock

Fixes: https://github.com/facebook/jscodeshift/issues/600

Migrate from chalk to picocolors

---

package.json

Fixes: https://github.com/facebook/jscodeshift/issues/606

Specify node >=16 as supported in package.json engines field

---

bin/__tests__/jscodeshift-test.js
package.json
utils/testUtils.js
yarn.lock

Fixes: https://github.com/facebook/jscodeshift/issues/608

Replace `mkdirp` with `fs.mkdirSync(path, { recursive: true })`

---

.eslintrc
package.json
yarn.lock

Fixes: https://github.com/facebook/jscodeshift/issues/612
Verified that there are no lint errors
```console
$ yarn eslint
yarn run v1.22.22
$ /Users/trivikram/workspace/jscodeshift/node_modules/.bin/eslint
✨  Done in 0.65s.
```

Replace babel-eslint with @babel/eslint-parser

---

src/collections/ImportDeclaration.js
src/collections/__tests__/ImportDeclaration-test.js
src/collections/index.js

Adds utility methods for import specifiers (similar to the ones provided for `JSXElements`). 
[Import manipulation](https://www.hypermod.io/docs/guides/import-manipulation) is probably the most common operation you will do in a codemod, but there are quite a few edge cases to consider when doing so. 
For example,
- Insert imports / specifiers without duplication
- Renaming import paths
- Checking for imports (good for early exit conditions)
`insertImportDeclaration`
`insertImportSpecifiers`
`findImportDeclarations`
`findImportSpecifier`
`findDefaultSpecifier`
`hasImportSpecifier`
`hasDefaultImportSpecifier`
TBD

WIP: Addition of custom collection functions for importDeclarations/Specifiers

---

src/collections/ImportDeclaration.js
src/collections/__tests__/ImportDeclaration-test.js
src/collections/index.js

Adds utility methods for import specifiers (similar to the ones provided for `JSXElements`). 
[Import manipulation](https://www.hypermod.io/docs/guides/import-manipulation) is probably the most common operation you will do in a codemod, but there are quite a few edge cases to consider when doing so. 
For example,
- Insert imports / specifiers without duplication
- Renaming import paths
- Checking for imports (good for early exit conditions)
`insertImportDeclaration`
`insertImportSpecifiers`
`findImportDeclarations`
`findImportSpecifier`
`findDefaultSpecifier`
`hasImportSpecifier`
`hasDefaultImportSpecifier`
TBD
Previous PR: https://github.com/facebook/jscodeshift/pull/611

Addition of custom collection functions for importDeclarations/Specifiers

---

parser/tsOptions.js

Allow syntax like `import obj from "./something.json" with { type: "json" };`

Include importAttributes in tsOptions.js

---

.github/workflows/cr.yml
package.json
yarn.lock

This PR adds continuous preview releases to jscodeshift! 
Before running the workflow, we'd have to install the [app](https://github.com/apps/pkg-pr-new)!

feat: add pkg.pr.new

---

.github/workflows/cr.yml
package.json
yarn.lock

since it breaks older Node versions when it's in package.json.

Revert pkg-pr-new to using npx

---

src/collections/VariableDeclarator.js
src/collections/__tests__/VariableDeclarator-test.js

This fixes an edge case that we ran into where JSX tags are inadvertently renamed when they are "built-in" components like `<div>` or `<span>`. We should only consider capitalized tags as variable references (see [React docs](https://legacy.reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized)). For this PR I used the the [same regex](https://github.com/babel/babel/blame/368b512229d41147f5ea835a3dd7d5a256a5764e/packages/babel-types/src/validators/react/isCompatTag.ts#L3) as the JSX Babel transform for consistency. 
I understand that this logic is React-specific and there could be JSX usage that does not follow these conventions. Ideally this could be configurable.

Fix renameTo false positive for JSX tags

---

bin/__tests__/jscodeshift-test.js
package.json
src/Runner.js
utils/testUtils.js
yarn.lock

This PR would fix the deprecation warnings that appear during the installation of `jscodeshift`'s peer dependencies.
An example of such warnings can be reproduced by installing the `jscodeshift` CLI tool globally (`npm i -g jscodeshift`) or by installing any other package that has jscodeshift as a dependency. For instance, this is what the error looks like in my shell:
The testing of this PR was done by performing the following steps:
- Packing the app with updated dependencies into a tarball using `yarn pack`
- Installing it globally via `npm i -g ./path/to/tarball.tgz`
The results are as shown:
After this PR is merged, a release will be required to fix the error for all of the dependants.

chore: replace `temp` library with `tmp`

---

.changeset/polite-lizards-know.md
README.md
src/__testfixtures__/test-async-transform.input.js
src/__testfixtures__/test-async-transform.js
src/__testfixtures__/test-async-transform.output.js
src/__testfixtures__/test-sync-transform.input.js
src/__testfixtures__/test-sync-transform.js
src/__testfixtures__/test-sync-transform.output.js
src/__tests__/__snapshots__/testUtils-test.js.snap
src/__tests__/testUtils-test.js
src/testUtils.js

Currently the available [test utilities](https://github.com/facebook/jscodeshift?tab=readme-ov-file#unit-testing) exposed by the library helps a lot when developers need to test their custom transformation but they only support synchronous transformations.
I've seen others also asking about this feature ([reference1](https://github.com/facebook/jscodeshift/issues/516), [reference 2](https://github.com/facebook/jscodeshift/issues/454)) so I've decided to give it a try and update those utilities to be able to manage both sync and async transformations.
Please let me know if this is something that could potentially be adopted by `jscodeshift`.
Thanks.

Enable async tranformers in test utils

---

.changeset/new-mayflies-push.md
package.json
yarn.lock

Closes: https://github.com/facebook/jscodeshift/issues/534#issuecomment-2686191281
Resolved by: https://github.com/benjamn/recast/pull/1406

bumps recast to the latest to resolve jsx double brackets issue

---

.changeset/modern-chicken-judge.md
package.json
yarn.lock

Closes #653
Includes: https://github.com/benjamn/recast/pull/1415

Bump recast to 0.23.11 - resolve parse failure for Typescript tagged templates

---

website/src/content/docs/build/api-reference.mdx

This PR updates the API documentation to include the `findImportDeclarations` method for Collections.
The method `findImportDeclarations` already exists in the jscodeshift codebase, but is currently missing from the official documentation.  
This update documents its usage, parameters, and provides a usage example.
Adding this entry improves the discoverability of existing API features and enhances developer experience (DX).
Thanks for maintaining jscodeshift!

docs: add missing `findImportDeclarations` method to Collection API documentation

---

.changeset/small-kangaroos-beg.md
README.md

- Fix link to `recast` config options
- Add example for using `lineTerminator` which is a common issue

fix(readme): passing `recast` options
